// @ts-nocheck
// This file is automatically generated by Firebase Studio. Do not edit manually.

import { FirebaseOptions } from 'firebase/app';

// This configuration is used for local development and when environment variables are not set.
// For production deployments, especially on platforms like Netlify or Vercel,
// you should set these as environment variables.
export const firebaseConfig: FirebaseOptions = {
  projectId: "studio-9688338833-1fbbb",
  appId: "1:846396000808:web:f117278aa5356bea3a831d",
  apiKey: "AIzaSyDjmgOcAebnKxg7dPlyVuSYWkcaVJnM_as",
  authDomain: "studio-9688338833-1fbbb.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "846396000808",
};
