// @ts-nocheck
// This file is automatically generated by Firebase Studio. Do not edit manually.

import { FirebaseOptions } from 'firebase/app';

// This configuration is used for local development and when environment variables are not set.
// For production deployments, especially on platforms like Netlify or Vercel,
// you should set these as environment variables.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
